drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);

/**
- 스프링 부트 - 기본 SQL 스크립트를 사용해서 데이터베이스를 초기화하는 기능
: 메모리 DB는 애플리케이션이 종료될 때 함께 사라지기 때문에, 애플리케이션 실행 시점에 데이터베이스 테이블도 새로 만들어주어야 한다.
  JDBC나 JdbcTemplate를 직접 사용해서 테이블을 생성하는 DDL을 호출해도 되지만, 너무 불편하다.
: 스프링 부트는 SQL 스크립트를 실행해서 애플리케이션 로딩 시점에 데이터베이스를 초기화하는 기능을 제공한다.
: 다음 파일을 생성하자.
  위치가 src/test 이다. 이 부분을 주의하자. 그리고 파일 이름도 맞아야 한다.
  src/test/resources/schema.sql
: 실행 DDL sql log
  2023-03-09 14:33:27.231 DEBUG 26968 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from URL [file:/D:/INFLEARN_SPRING/spring_db_advance/source/itemservice-db/out/test/resources/schema.sql]
  2023-03-09 14:33:27.238 DEBUG 26968 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : 0 returned as update count for SQL: drop table if exists item CASCADE
  2023-03-09 14:33:27.265 DEBUG 26968 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : 0 returned as update count for SQL: create table item ( id bigint generated by default as identity, item_name varchar(10), price integer, quantity integer, primary key (id) )
 */